In [1]:
import pandas as pd
import numpy as np

In [14]:
data = pd.read_csv('new_IntegerArray.txt')

In [15]:
data.head()

54044
0  14108
1  79294
2  29649
3  25260
4  60660

In [16]:
array = data.to_numpy()
print(array)

[[14108]
 [79294]
 [29649]
 ...
 [74018]
 [71187]
 [91901]]


In [17]:
print(array.shape)

(99999, 1)


In [18]:
array.reshape(1,99999)

array([[14108, 79294, 29649, ..., 74018, 71187, 91901]])

In [19]:
print(array.shape)

(99999, 1)


In [20]:
array[2]

array([29649])

In [21]:
numbers = array.tolist()

In [112]:
file = open('new_IntegerArray.txt') ## read in numbers instead of strings!!!! very important
all_numbers = []
for line in file:
  all_numbers.append(int(line))
print(type(all_numbers))
print(type(all_numbers[2]))

<class 'list'>
<class 'int'>


In [98]:
print(type(numbers)) # number is a list of the input numbers(integers)
print(type(numbers[1]))

<class 'list'>
<class 'list'>


In [79]:
test = [4, 80, 70, 23, 9, 60, 68, 27, 66, 78, 12, 40, 52, 53, 44, 8, 49, 28, 18, 46, 21, 39, 51, 7, 87, 99, 69, 62, 84, 6, 79, 67, 14, 98, 83, 0, 96, 5, 82, 10, 26, 48, 3, 2, 15, 92, 11, 55, 63, 97, 43, 45, 81, 42, 95, 20, 25, 74, 24, 72, 91, 35, 86, 19, 75, 58, 71, 47, 76, 59, 64, 93, 17, 50, 56, 94, 90, 89, 32, 37, 34, 65, 1, 73, 41, 36, 57, 77, 30, 22, 13, 29, 38, 16, 88, 61, 31, 85, 33, 54  ]
len(test)

100

In [80]:
# use an algorithm that combines merge sort to first divide and conq with merge sort and at same time
# counting the inversed number, (by when once added the from the right, you should add in number of elements left 
# from a sorted list on the left)

In [110]:
def merge_sort_inv(a,b):
    result = 0
    combine = []
    i = j = 0
    while i<len(a) and j<len(b):
        if a[i]<=b[j]:
            combine.append(a[i])
            i+=1
        else:
            combine.append(b[j])
            j+=1
            result += len(a)-i  # very important as not ++1 but += how many left in a, as for both are sorted array!
    if i==len(a):
        combine.extend(b[j:])
    else:
        combine.extend(a[i:])
    return combine, result 

def sort_inverse(l,n):
    if n==1:
        return l,0
    else:        
        middle = n//2
        left_len = middle
        right_len = n-middle
        left, left_inv = sort_inverse(l[:middle],left_len)
        right, right_inv = sort_inverse(l[middle:],right_len)
        combine, split_inv = merge_sort_inv(left,right)      # combined list is very important, as to give a returned result for the combined array

        return combine, left_inv + right_inv + split_inv
    
    
### introducing merge_sort with this solution to help!   
    

In [111]:
%%time
sorted_number, inv = sort_inverse(all_numbers,len(all_numbers))
print(inv)

2407905288
CPU times: user 776 ms, sys: 7.97 ms, total: 784 ms
Wall time: 782 ms


In [94]:
%%time
sorted_number, inv = sort_inverse(test,len(test))
print(inv)
print(sorted_number)

2372
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
CPU times: user 2.7 ms, sys: 3 µs, total: 2.7 ms
Wall time: 2.64 ms


In [95]:
  
with open('IntegerArray.txt') as f:
    a = [int(x) for x in f]

def CountSplitInv(B,C):
    i = 0
    j = 0
    count = 0
    D = []
    while i<len(B) and j<len(C):
        D.extend([min(B[i],C[j])])
        if B[i] < C[j]:
            i = i + 1
        else:
            count +=len(B[i:])
            j+=1
    D.extend(B[i:])
    D.extend(C[j:])
    Z = count
    return D,Z

def Sort_Count(A):
    n = len(A)
    if n > 1:
        splitposition = n // 2
        B,X = Sort_Count(A[:splitposition])
        C,Y = Sort_Count(A[splitposition:])
        D,Z = CountSplitInv(B,C)
        return D,X+Y+Z
    else:
        return A,0



In [30]:
%%time
sorted_num,num = Sort_Count(numbers)

CPU times: user 24.5 s, sys: 8 µs, total: 24.5 s
Wall time: 24.5 s


In [31]:
print(num)

2407851245


In [85]:
def count_inversions(L):

    inversion_counter = 0

    def count(L):
        if len(L) <= 1:
            return L
        else:
            n = len(L)
            mid = n//2
            left = count(L[:mid])
            right = count(L[mid:])

            i, j = 0, 0

            nonlocal inversion_counter

            for k in range(n):
                if left[i] <= right[j]:
                    L[k] = left[i]
                    i += 1
                    if i == len(left):
                        L[k+1:] = right[j:]  # NOTE we have to use k+1
                        return L
                else:
                    L[k] = right[j]
                    j += 1

                    inversion_counter += len(left) - i

                    if j == len(right):
                        L[k+1:] = left[i:]
                        return L

    count(L)

    return inversion_counter


# L = list(reversed(range(6)))
# print(L)
# print(count_inversions(L))

[5, 4, 3, 2, 1, 0]
15


In [87]:
count_inversions(numbers)

2407851245

In [88]:
def mergeSort(a,b):

    c = []
    inversion = 0
    left1 = 0
    right1 = 0
    while left1 < len(a) and right1 < len(b):
        if a[left1] < b[right1]:
            c.append(a[left1])
            left1 = left1 + 1
        else:
            c.append(b[right1])
            inversion = inversion + len(a[left1:])
            right1 = right1 + 1

    if left1 >= len(a):
        c = c + b[right1:]
    else:
        c = c + a[left1:]

    return c, inversion


def merge(values):
    if len(values) == 1:
        return values, 0
    mid = len(values) // 2;
    (left, inv1) = merge(values[0:mid])
    (right, inv2) = merge(values[mid:])
    (total, inv3) = mergeSort(left, right)

    return total,inv1+inv2+inv3

In [89]:
a,b = merge(numbers)

In [91]:
# print(a)
print(b)

0
